### ISSUE TITLE
No mid slide back button

### ISSUE THREAD

**Issue by joshboon** [tombasche/agile-manifesto-presentation#1]
Hi Thomas,

I've put together a presentation using your framework and I'm excited to present using it next week! That said I have some long slides that I'd prefer to have displayed all at once but have to instead just hold the advance button. The issue is that if I go too far I have to go back to go forward again which can be a pain. Here's a sample slide that would be rad to just to have either pop up all at once or even better able to animate in two distinct blocks. I may dig in and see if I can come up with some weird stuff using the text format. Also don't mind the comments I just print my full deck so I have my notes handy too as  I present or if folks want a bit more colored in presentation, 
```
    obligations = Slide(
        heading="What legal and contractual obligations do we have?",
        text=DotPointText([
            "Our privacy policy",
#                       """  Provides a blanket policy outlining what data we collect and that the Partner owns it. """
            "FERPA",
#                       """  A collection of amendments for ensure student privacy and give students' a fair means for dispute of their education records.
# Types of data mentioned:
# Education records anything related to the student's current education or previous records
# Personal records as associated with educational records
# Directory records, name, email, public honors
# Note school official exception which can allow FERPA disclousure without consent. Must be provided explicitly by the institution in their policies and subjects us to FERPA under school control. """,
                        "GDPR",
#                       """ EU regulation regarding data protection for EU citizens clarifying processing and data holder rights. Specifically ensuring the data is handled legitimately and with clear ownership. """
                        "PIPEDA",
#                       """ Canadian PII laws, differs according to local body """
                        "Partners' security policies",
#                       """ These tend to be the most prescriptive for what requirments we as a supplier have to meet. """
                        "Partners' NDA's",
#                       """ These primarily focus on intellectual property"""
                        " Not required at this time:",
                        "* Califonia Comsumer Privacy Act",
#                       """ Applies to companies that make more the 25 mil and only to commecial companies not non-profits or gov"""
                        "* MA 201 CMR 17",
#                       """ Specifically ties name to either an identifier and/or financial information """
#                       "* PCI DSS",
#                       """ """
                        "* HIPAA"
#                       """ """
                        #"* Sarbanes-Oxley"
#                       """ built for public companies from the enron/worldcom scandals. """
      ]),
      border="&"
    )
```

**Comment by tombasche** [comment]
Hi Josh,

That should be fairly simple :) 
I'm thinking config to say `display_now=True`, and by organising text objects into `Block` objects which are animated independently. So if you specify a `Block` with a `display_now` then it will appear straight away (and a `Block` contains  1+ text objects.)

That should give enough flexibility I think to tinker around with different configurations. I'll get a start on it this evening!

As for a mid-slide back button, the interesting thing is that the back button lives at a higher level from the slides, if that makes sense; being able to listen for a back request and 'undoing' printed text might be a bit tricky mid-slide, but I'll have look and see what I can do.

Sidenote: I'm stoked that something else is using this!

**Comment by joshboon** [comment]
Hi Thomas, 

That sounds great! Even just a display_now=True would be all I would need for now. As for the mid-slide button maybe make just an escape valve to reset the slide and bring the control back to the event listener? 

Sidenote: My presentation is on data risk so if you have a need for a data risk deck or presentation I'm all ears. I'm looking forward to sharing it with the team :) 

-- 
Josh Boon ( he/him/they/them) | [ http://joshboon.com/ | joshboon.com ] 
+1.719.298.2246 | alwayscurious@joshboon.com

**Comment by tombasche** [comment]
Turns out I had an `animated_heading` option I had completely forgot about, so just added an `animated_body` option. Use is like so:

```
obligations = Slide(
    heading="What legal and contractual obligations do we have?",
    text=DotPointText(
        [
            "Our privacy policy",
            "FERPA",
            "GDPR",
            "PIPEDA",
            "Partners' security policies",
            "Partners' NDA's",
            " Not required at this time:",
            "* Califonia Comsumer Privacy Act",
            "* MA 201 CMR 17",
            "* HIPAA",
        ]
    ),
    animated_body=False,
    border="&",
)
```

**Comment by joshboon** [comment]
Thanks for this, oddly it looks like it bashes the border and layout. 
![withinstant](https://user-images.githubusercontent.com/4528945/99262577-287d5680-27ec-11eb-8e29-15b01e2549e4.png)
![withoutinstant](https://user-images.githubusercontent.com/4528945/99262582-2915ed00-27ec-11eb-9441-0d8524e5e010.png)

**Comment by tombasche** [comment]
Hmm that is weird ... I’ll raise a separate issue and check that out!
